# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  name: Dev

steps:
  - script: |
      sudo apt update -y
      sudo apt install unzip -y
      

  - task: TerraformInstaller@1
    inputs:
      terraformVersion: '1.5.3'
  - script: |
      sudo cp /home/praveen14/myagent/_work/_tool/terraform/1.5.3/x64/terraform /usr/bin
