name: ImageCreation_$(Date:yyyyMMdd)$(Rev:.r)

trigger:

  - main

jobs:

  - job: build

    pool:

      name: Dev

    steps:

      - task: Docker@2

        displayName: Login to DockerHub

        inputs:

          command: login

          containerRegistry: dockerhubconnection

      - task: Docker@2

        displayName: Build Image

        inputs:

          command: build

          Dockerfile: '**/Dockerfile'

          repository: prav911/images

          tags: |

            tag1

      - task: Docker@2

        displayName: Push Image

        inputs:

          command: push

          repository: prav911/images

          tags: |

            tag1
