---
- name: copying ssh key and updating sudoers
  vars:
    ansible_host_key_checking: false
  hosts: servers
  remote_user: ansible
  gather_facts: false
  tasks:
    - name: copying file with playbook
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: ~/.ssh/id_rsa.pub
    - name: Copy SSh Key | copying shh key to remote host
      authorized_key:
        user: "ansible"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        path: ~/.ssh/authorized_keys
        manage_dir: False
...